# Generated by Django 5.2.7 on 2025-10-04 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedServer',
            fields=[
                ('player_history', models.JSONField(auto_created=True, blank=True, default=list, verbose_name='player history')),
                ('ip', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('last_checked', models.DateTimeField(verbose_name='last checked')),
                ('max_players', models.IntegerField(verbose_name='max players')),
                ('online_players', models.JSONField(blank=True, default=list, verbose_name='online players')),
                ('player_count', models.IntegerField(default=0, verbose_name='player count')),
                ('mc_version', models.CharField(max_length=32, verbose_name='minecraft version')),
                ('mc_motd', models.TextField(verbose_name='motd')),
                ('mc_bedrock', models.BooleanField(verbose_name='bedrock')),
                ('mc_latency', models.FloatField(verbose_name='ping')),
                ('mc_favicon', models.TextField(verbose_name='image')),
            ],
        ),
    ]
