# Generated by Django 5.2.7 on 2025-10-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverchecker', '0002_trackedserver_last_check_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedserver',
            name='label',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
